export const dummyProjects = [
    {
      name: "Project A",
      startDate: "2025-01-15",
      endDate: "2025-12-31",
      description: "This is a description of Project A.",
      projectManager: "John Doe",
      id: "A9F4K2B3V5",
    },
    {
      name: "Project B",
      startDate: "2025-02-01",
      endDate: "2025-11-30",
      description: "This is a description of Project B.",
      projectManager: "Jane Smith",
      id: "B1G8N5Y3X4",
    },
    {
      name: "Project C",
      startDate: "2025-02-01",
      endDate: "2025-11-30",
      description: "This is a description of Project C.",
      projectManager: "Sana Marin",
      id: "C6J1R7I8M3",
    },
    {
      name: "Project D",
      startDate: "2025-02-01",
      endDate: "2025-11-30",
      description: "This is a description of Project D.",
      projectManager: "Tom Cruise",
      id: "D4K2W9J5N0",
    },
    {
      name: "Project E",
      startDate: "2025-03-01",
      endDate: "2025-09-30",
      description: "This is a description of Project E.",
      projectManager: "Emily Davis",
      id: "E7F3P8B4Q2",
    },
    {
      name: "Project F",
      startDate: "2025-04-01",
      endDate: "2025-08-31",
      description: "This is a description of Project F.",
      projectManager: "Michael Jackson",
      id: "F1H7V5X9A0",
    },
    {
      name: "Project G",
      startDate: "2025-05-01",
      endDate: "2025-12-31",
      description: "This is a description of Project G.",
      projectManager: "Sarah Lee",
      id: "G8P2L5C1Y4",
    },
  ];